### ISSUE TITLE
How to run tests locally before attempting a PR to expand compatibility?

### ISSUE THREAD

**Issue by simkimsia** [AltSchool/dynamic-rest#258]
Hi there, 

I read https://github.com/AltSchool/dynamic-rest/blob/master/CONTRIBUTING.md but I am still not too sure how to run tests locally before submitting a PR.

I am using this for my own production and for a brand new project, we like to use DREST with the following:

- python 3.7.0
- DRF 3.8.2
- Django 1.11.16

I be happy to help expand compatibility so long as it's within my capability.

Can advise?

**Comment by simkimsia** [comment]
I created my own virtualenv that uses 3.6.6 python and DRF 3.8

I fixed the issue in my own fork regarding the missing `replace_methodname` function see #246 

But I came across two other situations that made me unable to tell whether I was running the tests wrongly or it's due to DRF3.8

My steps are:

1. create the virtualenv using 3.6.6 python
2. change the requirements so that drf3.8 is included (see https://github.com/simkimsia/dynamic-rest/commit/fd47de78fa32309081e96b6a8e0da6c32d1e1c50)
3. `pip install -r install_requires_python3.txt`
4. `ip install -r requirements.txt`
5. `py.test`

```
――――――――――――――――――――――― ERROR collecting benchmarks/test_bench.py ――――――――――――――――――――――――
benchmarks/test_bench.py:12: in <module>
    from .models import Group, Permission, User
benchmarks/models.py:4: in <module>
    class User(models.Model):
../../PythonApps/python366-dynamic-rest/lib/python3.6/site-packages/django/db/models/base.py:108: in __new__
    "INSTALLED_APPS." % (module, name)
E   RuntimeError: Model class benchmarks.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

――――――――――――――――――――――――― ERROR collecting tests/test_router.py ――――――――――――――――――――――――――
tests/test_router.py:14: in <module>
    from tests.urls import urlpatterns  # noqa  force route registration
tests/urls.py:26: in <module>
    url(r'^', include(router.urls))
../../PythonApps/python366-dynamic-rest/lib/python3.6/site-packages/rest_framework/routers.py:101: in urls
    self._urls = self.get_urls()
../../PythonApps/python366-dynamic-rest/lib/python3.6/site-packages/rest_framework/routers.py:363: in get_urls
    urls = super(DefaultRouter, self).get_urls()
../../PythonApps/python366-dynamic-rest/lib/python3.6/site-packages/rest_framework/routers.py:261: in get_urls
    routes = self.get_routes(viewset)
dynamic_rest/routers.py:284: in get_routes
    routes += self.get_relation_routes(viewset)
dynamic_rest/routers.py:329: in get_relation_routes
    initkwargs={}
E   TypeError: __new__() missing 1 required positional argument: 'detail'
```

**Comment by simkimsia** [comment]
Okay, I realised the trick is to run 

`py.test tests/` and I found another issue for dynamic-rest to work with DRF3.8. Will fix this.
